apiVersion: nova.openstack.org/v1beta1
kind: NovaCompute
metadata:
  name: nova-compute-{{ .WorkerOspRole }}
  namespace: openstack
spec:
  novaSecret: {{ .NovaSecret }}
  neutronSecret: {{ .NeutronSecret }}
  placementSecret: {{ .PlacementSecret }}
  transportURLSecret: {{ .TransportURLSecret }}
  novaComputeCpuDedicatedSet: {{ .NovaComputeCPUDedicatedSet }}
  {{ end }}
  {{ if not (eq .NovaComputeCPUSharedSet "") }}
  novaComputeCpuSharedSet: {{ .NovaComputeCPUSharedSet }}
  {{ end }}
  {{ if not (eq .NovaReservedHostMemory 0) }}
  novaReservedHostMemory: {{ .NovaReservedHostMemory }}
  {{ end }}
  novaComputeImage: docker.io/tripleotrain/rhel-binary-nova-compute:current-tripleo
  roleName: {{ .WorkerOspRole }}
